
function pupil=annpupil(fxx,fyy,ri,ro)
% pupil = annpupil(fxx,fyy,ri,ro). This function creates pupil function with inner and outer radii of ri and
% ro as a logical array. For circular pupils define ri=ro. fxx and fyy are the
% variables generated by meshgrid.

    if (ri == ro) 
        pupil= (fxx.^2 + fyy.^2) <= ri^2;
    elseif (ri>ro)
        print('Inner radius larger than outer radius!');
        return;
    else
        pupil=(ri^2<=(fxx.^2 + fyy.^2) & (fxx.^2 + fyy.^2)<=ro^2);
    end
    pupil=double(pupil);
    
end
